### ISSUE TITLE
Differential counts

### ISSUE THREAD

**Issue by vetmohit89** [scottgroup/coco#3]
Hello,

I have got counts after coco cc command. Can I use any any method such as deseq2 for differential counts? 

Another concern: Can I use this pipeline for anyother RNA biotype (snRNA or miRNA etc) ?

Thank you

**Comment by Gabrielle-DF** [comment]
Yes, you can use differential analysis tools such as DESeq2. I the particular case of DESeq2, you will need to round the counts to remove decimal values.

CoCo can work with any biotype you want by simply setting the --biotypes argument in the correct_annotation step. By default, the following biotypes are corrected: snoRNA, scaRNA, tRNA, miRNA, snRNA.
