### ISSUE TITLE
Output_COCO CC

### ISSUE THREAD

**Issue by vetmohit89** [scottgroup/coco#5]
Dear, 

I followed coco run modes as described in manual. I am trying to understand what is the meaning of these gene_id and gene_name: 
![image](https://github.com/scottgroup/coco/assets/110649675/4761ca84-edb2-4847-a3fb-f5d5c8521488)

**Comment by Gabrielle-DF** [comment]
Hello,
These entries are from the paper [https://doi.org/10.1093/nar/gkaa028](https://doi.org/10.1093/nar/gkaa028), they are described in supplementary file 1. For the gene_names, they were generated randomly, you can simply replace them by the gene_ids or anything you want. If you have more questions on these genes, you can refer to the authors through: [https://github.com/GaspardR/snakemake_blockbuster](https://github.com/GaspardR/snakemake_blockbuster).
